### ISSUE TITLE
Weekly Scrum Mar 18

### ISSUE THREAD

**Issue by SamBaumann** [SamBaumann/4806-TrustReviews#11]
What have I done this week?

Set up Heroku online Database connection via PG Admin GUI, worked on presentation concerning automated browser testing

What will I do next week?

Work on implementing database changes to reflect actual code, implement additional features (users, etc.)

What is holding me back?

Motivation and recollection to continually push and commit on a regular basis

**Comment by davidou997** [comment]
What have I done this week?

Viewed React resources on how to create multiple pages.

What will I do next week?

Add frontend for a profile page, a page per individual product, and a product browsing page

What is holding me back?

Other work from other courses.

**Comment by yusufjaamac** [comment]
What have I done this week?
Learned about react dynamic webpages abilities

What will I do next week?
Creating 2 pages first page to browse products and second page to view each product

What is holding me back?
Busy schedule

**Comment by harrywinton5** [comment]
1. What have I done this week?

- Upgrade database for users

- Upgrade weak password detection

- Add new feature: database for review system

2. What will I do next week?
Adding review and rating system

3. What is holding me back?
Need more time to work on new feature

**Comment by yasinjaamac** [comment]
What have I done this week?

Learned more regarding cypress testing with additional tests. Learned more regarding react including more pages
What will I do next week?

Work on adding more tests and add more functionality for front end for our pages

What is holding me back?

Time constraint
