### ISSUE TITLE
Weekly Scrum Mar 11

### ISSUE THREAD

**Issue by SamBaumann** [SamBaumann/4806-TrustReviews#6]
**What have I done this week?**

Initial commit w/ user logins and default framework, Presentation research & coordination. Basic formatting and bureaucratic responsibilities (Kanban, ReadMe, Checklist, Schema, etc. etc.)

**What will I do next week?**

Additional updates to database to handle Users, Products and Reviews, and additional features

**What is holding me back?**

A general lack of understanding of Git, Branches, Node and how to merge it all to a Database structure.

**Comment by davidou997** [comment]
**What have I done this week?**
Learned about React and created the initial React application and added basic local add and delete product functionality.

**What will I do next week?**
Developing relevant web pages on the application, such as the account, browsing, and individual product pages.

**What is holding me back?**
Lack of understanding in Git pull and merge requests and the React framework. Time constraints with other coursework.

**Comment by yasinjaamac** [comment]
What have I done this week?

Added end 2 end tests for the front end class. Tested the add and remove product using cypress. Read me. Researched react framework and cypress

What will I do next week?

Adding additional end 2 end tests and developing database

What is holding me back?

New to react framework

**Comment by yusufjaamac** [comment]
What Have I done this week: Setup Heroku for app deployment, UML class diagram. Introduced to react very unique and useful library

What will i do next week: Add more features for users to web page for sophistication. 
What is holding me back: Github features need to learn more about them.

**Comment by harrywinton5** [comment]
1. What have I done this week?

- Set up database for users
- Add user registration system
- Add user authentication system

2. What will I do next week?

Adding review and rating system

3. What is holding me back?

New to node.js
